# fly.toml app configuration file generated for ticket-teams on 2025-04-17T21:16:24+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ticket-teams'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "ticket_data"
  destination = "/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
